/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.detailsScreens;


import javax.swing.*;

/**
 *
 * @author Nam
 */
public abstract class PostDetailsForm extends javax.swing.JFrame {
    private String link;
    private String header;
    /**
     * Creates new form Form
     */
    public PostDetailsForm() {
        initComponents();
    }
    public PostDetailsForm(String title) {
        initComponents();
        getPostDetails(title);
        tfTitle.setText(title);
        tfLink.setText(link);
    }

    public abstract void getPostDetails(String title);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {
        initOptionalComponent();
        panelPostDetailsForm = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        lbLink = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfLink = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPostDetailsForm.setBackground(new java.awt.Color(255, 255, 255));

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(0, 102, 102));
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setText(header);

        lbLink.setForeground(new java.awt.Color(0, 102, 102));
        lbLink.setText("Link");

        btnThoat.setBackground(new java.awt.Color(102, 0, 0));
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.setMargin(new java.awt.Insets(3, 14, 3, 14));
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lbTitle.setForeground(new java.awt.Color(0, 102, 102));
        lbTitle.setText("Title");

        tfTitle.setEditable(false);
        tfTitle.setForeground(new java.awt.Color(0, 102, 102));
        tfTitle.setCaretColor(new java.awt.Color(0, 102, 102));
        tfTitle.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfTitle.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfTitle.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfTitle.setSelectionColor(new java.awt.Color(0, 102, 102));

        tfLink.setEditable(false);
        tfLink.setForeground(new java.awt.Color(0, 102, 102));
        tfLink.setCaretColor(new java.awt.Color(0, 102, 102));
        tfLink.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfLink.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfLink.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfLink.setSelectionColor(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelPostDetailsFormLayout = new javax.swing.GroupLayout(panelPostDetailsForm);
        panelPostDetailsForm.setLayout(panelPostDetailsFormLayout);

        panelPostDetailsFormLayout.setHorizontalGroup(
                panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(btnThoat)
                                .addContainerGap(278, Short.MAX_VALUE))
                        .addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                                                .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(getlbTitle())
                                                                        .addComponent(getlbLink()))
                                                                .addGap(59, 59, 59)
                                                                .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(getTfLink())
                                                                        .addComponent(getTfTitle()))
                                                        ).addGroup(horizontalOptionalGroup(panelPostDetailsFormLayout))
                                                )
                                                .addGap(64, 64, 64)))
                                .addContainerGap())
        );
        panelPostDetailsFormLayout.setVerticalGroup(
                panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPostDetailsFormLayout.createSequentialGroup().addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lbHeader)
                                        .addGap(23, 23, 23)
                                        .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbLink)
                                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(panelPostDetailsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbTitle)
                                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        )
                                ).addGroup(verticalOptionalGroup(panelPostDetailsFormLayout))
                                .addGroup(panelPostDetailsFormLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnThoat)
                                        .addContainerGap(26, Short.MAX_VALUE)
                                ))

        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPostDetailsForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPostDetailsForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    };// </editor-fold>//GEN-END:initComponents

    // Method to init optional components
    public abstract void initOptionalComponent();

    // Group for optional component
    public abstract GroupLayout.SequentialGroup horizontalOptionalGroup(
            GroupLayout panelPostDetailsFormLayout);

    // Group for optional component
    public abstract GroupLayout.SequentialGroup verticalOptionalGroup(
            GroupLayout panelPostDetailsFormLayout);

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    // ----------------- start to code --------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    };

    // ------------ Getter and Setter ---------------


    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public JLabel getlbLink() {
        return lbLink;
    }

    public JLabel getlbTitle() {
        return lbTitle;
    }

    public JTextField getTfLink() {
        return tfLink;
    }

    public JTextField getTfTitle() {
        return tfTitle;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbLink;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel panelPostDetailsForm;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
