/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.ListOfRedditPosts;
import models.KeyWord;
import models.RedditPost;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nam
 */
public abstract class logScreen extends javax.swing.JFrame {


    String key = "";

    /**
     * Creates new form Form
     */
    public logScreen() {
        initComponents();
    }

    public logScreen(KeyWord keyWord) {
        initComponents();
//        this.keyWord = keyWord;
//        this.redditPostListByKeyWord.setRedditPostList(redditPostList.getRedditPostByKeyWord(keyWord.getWord()));
//        System.out.println(this.keyWord);
//        System.out.println(this.redditPostListByKeyWord.getRedditPostList().size());
//        tfKeyWord.setText(keyWord.getWord());
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public abstract void initComponents();
    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepActionPerformed


    private void btnSapXepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSapXepMouseClicked
        display();
    }//GEN-LAST:event_btnSapXepMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void redditPostLogPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redditPostLogPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_redditPostLogPanelMouseClicked

    // ---------------------- START TO CODE HERE ---------------------
    private KeyWord keyWord = null;
    private final ListOfRedditPosts redditPostList = new ListOfRedditPosts();
    private ListOfRedditPosts redditPostListByKeyWord = new ListOfRedditPosts();
    private ListOfRedditPosts currentRedditPostListByKeyWord;
    // ----------- display ----------
    public abstract void display();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel redditPostLogPanel;
//    private javax.swing.JButton btnSapXep;
//    private javax.swing.JButton btnThoat;
//    private javax.swing.JComboBox<String> cbTangDan;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTable tRedditPost;
//    private javax.swing.JTextField tfKeyWord;
    // End of variables declaration//GEN-END:variables
}
