/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.CollectionBoardScreen;

import models.lists.ListOfBlogs;
import models.Blog;
import models.Collection;

import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Nam
 */
public class BlogLogScreen extends javax.swing.JFrame {

    
    String key = "";

    /**
     * Creates new form Form
     */
    public BlogLogScreen() {
        initComponents();
    }

    public BlogLogScreen(Collection collection) {
        initComponents();
        this.collection = collection;
        this.blogListByCollection.setBlogList(collection.getBlogByCollection(blogList.getBlogList()));
        tfCollection.setText(collection.getName());
        display();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuaXoaHoKhau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCollection = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBlog = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSuaXoaHoKhau.setBackground(new java.awt.Color(255, 255, 255));
        PanelSuaXoaHoKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        PanelSuaXoaHoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSuaXoaHoKhauMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CÁC BLOG LIÊN QUAN TỚI COLLECTION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Collection");

        tfCollection.setEditable(false);
        tfCollection.setForeground(new java.awt.Color(0, 102, 102));
        tfCollection.setCaretColor(new java.awt.Color(0, 102, 102));
        tfCollection.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        tfCollection.setMargin(new java.awt.Insets(4, 6, 4, 6));
        tfCollection.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        tfCollection.setSelectionColor(new java.awt.Color(0, 102, 102));

        tBlog.setForeground(new java.awt.Color(0, 102, 102));
        tBlog.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Title", "Description", "Link"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBlog.setGridColor(new java.awt.Color(188, 206, 206));
        tBlog.setRowHeight(26);
        tBlog.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tBlog.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tBlog.setShowGrid(true);
        tBlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBlogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tBlog);

        btnThoat.setBackground(new java.awt.Color(102, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.setBorderPainted(false);
        btnThoat.setMargin(new java.awt.Insets(4, 10, 4, 10));
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSuaXoaHoKhauLayout = new javax.swing.GroupLayout(PanelSuaXoaHoKhau);
        PanelSuaXoaHoKhau.setLayout(PanelSuaXoaHoKhauLayout);
        PanelSuaXoaHoKhauLayout.setHorizontalGroup(
                PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addContainerGap(999, Short.MAX_VALUE)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                        .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
        );
        PanelSuaXoaHoKhauLayout.setVerticalGroup(
                PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelSuaXoaHoKhauLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnThoat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(PanelSuaXoaHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(tfCollection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1141, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PanelSuaXoaHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 630, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PanelSuaXoaHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void tBlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBlogMouseClicked
        DefaultTableModel model = (DefaultTableModel)tBlog.getModel();
        int indexRow = tBlog.getSelectedRow();
        key = String.valueOf(model.getValueAt(indexRow, 0).toString());
        String description = String.valueOf(model.getValueAt(indexRow, 1).toString());
        String link = String.valueOf(model.getValueAt(indexRow, 2).toString());

//        System.out.println(this.key);
        BlogDetailsForm newDetailsForm = new BlogDetailsForm(key, link, description, collection.getName());
        newDetailsForm.setVisible(true);
    }//GEN-LAST:event_tBlogMouseClicked

    
    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void PanelSuaXoaHoKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuaXoaHoKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelSuaXoaHoKhauMouseClicked

    // ------------ Start to code -------------
    private void display() {
        this.currentBlogListByCollection = blogListByCollection;

        DefaultTableModel defaultTableModel = (DefaultTableModel) tBlog.getModel();
        defaultTableModel.getDataVector().removeAllElements();
        defaultTableModel.fireTableDataChanged();
        for (Blog blog : currentBlogListByCollection.getBlogList()) {
            String data[] = {blog.getTitle(), blog.getDescription(), blog.getLink()};
            defaultTableModel = (DefaultTableModel) tBlog.getModel();
            defaultTableModel.addRow(data);
        }
    }

    private Collection collection = null;
    private  final ListOfBlogs blogList = new ListOfBlogs();
    private ListOfBlogs blogListByCollection = new ListOfBlogs();
    private ListOfBlogs currentBlogListByCollection;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BlogLogScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(BlogLogScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(BlogLogScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(BlogLogScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlogLogScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSuaXoaHoKhau;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tBlog;
    private javax.swing.JTextField tfCollection;
    // End of variables declaration//GEN-END:variables
}
